# Generated by Django 5.2 on 2025-05-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('account_manager_image', models.CharField(max_length=255)),
                ('sales_manager_image', models.CharField(max_length=255)),
                ('account_manager', models.CharField(max_length=255)),
                ('sales_manager', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('type_of_client', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('monthly_budgets', models.CharField(max_length=50)),
                ('balance_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_rub', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loans_rub', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client_module_table_0001_client',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='client_management.client')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'db_table': 'client_module_table_0002_offer',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('exchange_extras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='client_management.client')),
            ],
            options={
                'verbose_name': 'Условие оплаты',
                'verbose_name_plural': 'Условия оплаты',
                'db_table': 'client_module_table_0003_payment_term',
            },
        ),
    ]
